/**
* Generated by @proofgeist/fmdapi package
* 2022-07-01 10:57 am -05:00
* https://github.com/proofgeist/fmdapi
* DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
*/

import { z } from "zod";
import { DataApi } from "@proofgeist/fmdapi";
export const ZUser = z.object({
    "id": z.string(),
    "email": z.string(),
    "name": z.string(),
    "emailVerified": z.string(),
    "image": z.string(),
    "role": z.string(),
    "test": z.string()
});
export type TUser = z.infer<typeof ZUser>;
if (!process.env.FM_DATABASE)
    throw new Error("Missing env var: FM_DATABASE");
if (!process.env.FM_SERVER)
    throw new Error("Missing env var: FM_SERVER");
if (!process.env.FM_USERNAME)
    throw new Error("Missing env var: FM_USERNAME");
if (!process.env.FM_PASSWORD)
    throw new Error("Missing env var: FM_PASSWORD");
export const client = DataApi<any, TUser>({
    auth: { username: process.env.FM_USERNAME, password: process.env.FM_PASSWORD },
    db: process.env.FM_DATABASE,
    server: process.env.FM_SERVER,
    layout: "nextauth_user"
}, {
    fieldData: ZUser
});
